apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: secret-http
type: Opaque
data:
  username: YWRtaW4=   # Base64 encoded value of 'admin'
  password: cGFzc3dvcmQ=   # Base64 encoded value of 'password' 
