---
- name: RHDE and AAP Demo
  hosts:
    - edge_management
  tasks:
    - name: Install management node
      ansible.builtin.include_role:
        name: ../../../../common/roles/config_edge-mgmt-node
      vars:
        gitea_user_repos_template: ../templates/gitea_repos