---
- name: RHDE and AAP Demo
  hosts:
    - edge_management
  tasks:

#    - name: Install management node
#      ansible.builtin.include_role:
#        name: ../../../../roles/setup_rh_edge_mgmt_node
#      vars:
#        include_image_builder: false
#        include_fdo: false
#        include_gitea: false
#        include_aap: false

#    - name: Install management node
#      ansible.builtin.include_role:
#        name: ../../../../roles/config_rh_edge_mgmt_node
#      vars:
#        include_image_builder: false
#        include_fdo: false
#        include_gitea: false
#        include_aap: false






    - name: Install management node
      ansible.builtin.include_role:
        name: ../../../../roles/setup_rh_edge_mgmt_node

    - name: Config management node
      ansible.builtin.include_role:
        name: ../../../../roles/config_rh_edge_mgmt_node
      vars:
        image_builder_admin_name: admin
        image_builder_admin_password: R3dh4t1!
        gitea_admin_repos_template: ../templates/gitea_admin_repos
        gitea_user_repos_template: ../templates/gitea_user_repos
        aap_config_template: ../templates/aap_config.j2
        aap_repo_name: aap

