---
- name: "Create MicroShift embedded image"
  hosts: image_builder
  become: true
  gather_facts: true
  vars_files:
  - ../vars/main.yml
  tasks:

######### Create image 

        # Create microshift image
        - become: true
          ansible.builtin.import_role:
            name: infra.osbuild.builder

        - debug:
            msg:  
              - "Now:"
              -   "1) Download the ISO image from: http://{{ ansible_host }}/{{ builder_blueprint_name }}/images/{{ builder_blueprint_output['current_version'] }}/{{ builder_blueprint_name }}_edge-simplified-installer.iso"
              -   "2) Use the ISO to install the edge device"
              -   "3) SSH to the device and get the kubeconfig file located in /var/lib/microshift/resources/kubeadmin/<hostname that can be reached>/"
                        
