---
builder_blueprint_name: production-{{ gitea_user_name }}{{ user_number }}
builder_request_timeout: 300
builder_wait_compose_timeout: 2400
builder_compose_type: edge-commit
builder_skip_repo: true
builder_compose_pkgs:
  - microshift
  - microshift-greenboot
  - NetworkManager-wifi
  - firewalld
  - openshift-clients
  - podman
  - vim-enhanced
  - NetworkManager-wifi
  - "fuse-overlayfs"
  - "setroubleshoot-server"
  - "slirp4netns"
  - "net-tools"
  - "git"
  - "python3-pip"
  - "python3-inotify"
builder_compose_customizations:
  user:
    name: "{{ rhde_user_name }}"
    description: "Admin user"
    password: "{{ rhde_user_password }}"
    groups: ["users", "wheel"]
  services:
    enabled: ["microshift"]
  firewall.services:
    enabled: ["80/tcp", "443/tcp", "6443/tcp"]
