---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: game2048
spec:
  selector:
    app: game2048
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: game2048
spec:
  port:
    targetPort: 8081 
  to:
    kind: Service
    name: test-service
    weight: 10