---

- name: Create resources from manifest in Gitea using local OC client
  hosts:
    - all
  tasks:
    - name: Download manifest
      shell: |
        curl -k -o app.yaml -H "Authorization: Basic $(echo -n '{{  gitea_user_name }}{{ user_number  }}:{{ gitea_user_password }}{{ user_number  }}' | base64)" {% raw %}{{ manifest }} {% endraw %}     
        
    - name: Deploy YAML files
      become: true
      shell: |
        oc --kubeconfig /var/lib/microshift/resources/kubeadmin/kubeconfig create -f app.yaml

    - name: remove app manifest
      ansible.builtin.file:
        path: "app.yaml"
        state: absent