 
---

- name: compose an image via Image Builder
  hosts:
    - all

  tasks:

    - name: Import Image definition variables from remote file
      block:

            - name: Create a tmp directory if it does not exist 
              ansible.builtin.file:
                path: /tmp/{{ ansible_host }}/repos/{{ gitea_user_name }}{{ user_number }}"
                state: directory

            - name: Clone repo 
              ansible.builtin.shell:            
                cmd: "git clone http://{{ gitea_user_name }}{{ user_number }}:'{{  gitea_user_password }}{{ user_number  }}'@{{ ansible_host }}:3001/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ images_repo }}{% endraw %}.git /tmp/{{ ansible_host }}/repos/{{ gitea_user_name }}{{ user_number }}/images"
                #chdir: "/tmp/{{ ansible_host }}/repos/{{ gitea_user_name }}{{ user_number }}"

            - name: Import image definition
              ansible.builtin.include_vars:
                file: "/tmp/{{ ansible_host }}/repos/{{ gitea_user_name }}{{ user_number }}/images/{% raw %}{{ image_definition_file }}{% endraw %}"

            - name: Import version to deploy
              ansible.builtin.include_vars:
                file: "/tmp/{{ ansible_host }}/repos/{{ gitea_user_name }}{{ user_number }}/images/{% raw %}{{ image_deploy_file }}{% endraw %}"

            - name: Remove tmp directory
              ansible.builtin.file:
                path: "/tmp/{{ ansible_host }}/repo/{{ gitea_user_name }}{{ user_number }}"
                state: absent

      delegate_to: localhost



{% raw %}
    - ansible.builtin.debug:
        msg: "Selected version: {{ production_image_version }}"


    - name: Export the compose artifact
      infra.osbuild.get_all_finished_images:
      register: all_images


    - name: Get version number if version = latest
      block:
        - name: Get all image versions from blueprint {{ builder_blueprint_name }}
          set_fact:
            all_image_versions_blueprint: "{{ all_images|json_query(blueprint_query) }}"
          vars:
            blueprint_query: "result.finished[?blueprint =='{{ builder_blueprint_name }}'].version"


        - name: Get latest image versions from blueprint {{ builder_blueprint_name }}
          set_fact:
            latest_image_version_blueprint: "{{ all_image_versions_blueprint | max}}"


        - ansible.builtin.debug:
            msg: "Latest image version for blueprint {{ builder_blueprint_name }} is: {{ latest_image_version_blueprint }}"

        - name: Set version number
          set_fact:
            production_image_version: "{{ latest_image_version_blueprint }}"

      when: production_image_version == "latest"


    - set_fact:
        all_image_from_blueprint: "{{ all_images|json_query(blueprint_query) }}"
      vars:
        blueprint_query: "result.finished[?blueprint =='{{ builder_blueprint_name }}']"


    - set_fact:
        image_id:  "{{ all_image_from_blueprint|json_query(id_query) | join(',')  }}"
      vars:
        id_query: "[?version =='{{ production_image_version }}'].id"

    - debug:
        msg:  "Selected image id: {{ image_id }}"

{% endraw %}


    - name: Create a tmp directory if it does not exist
      ansible.builtin.file:
        path:  /tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}
        state: directory

    - name: Export the compose artifact
      infra.osbuild.export_compose:
        compose_id: "{% raw %}{{ image_id }}{% endraw %}"
        dest: "/tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/{{ gitea_user_name }}{{ user_number }}-image_{% raw %}{{ image_id }}{% endraw %}.tar"

    - name: Untar artifact
      ansible.builtin.unarchive:
        src: /tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/{{ gitea_user_name }}{{ user_number }}-image_{% raw %}{{ image_id }}{% endraw %}.tar
        dest: /tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/
        remote_src: true


## IN ORDER TO WORKAROUND WHILE THAT'S FIXED WE CAN JUST COPY THE NEW FILES IN THE HTTP SERVER


    - name: Create ostree-repo users directory if it does not exist
      ansible.builtin.file:
        path:  /var/www/html/user-repos/{{ gitea_user_name }}{{ user_number }}
        state: directory

    - name: Remove old repo directory if it existed
      ansible.builtin.file:
        path: /var/www/html/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/repo
        state: absent

    - name: Copy the new repo
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/repo
        dest: /var/www/html/user-repos/{{ gitea_user_name }}{{ user_number }}


    - name: Remove tar file
      ansible.builtin.file:
        path: "/tmp/user-repos/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/{{ gitea_user_name }}{{ user_number }}-image_{% raw %}{{ image_id }}{% endraw %}.tar"
        state: absent

    - name: Remove tmp directory
      ansible.builtin.file:
        path: "/tmp/user-repos/{{ gitea_user_name }}{{ user_number }}"
        state: absent

    - name: Restore context on directory
      ansible.builtin.command: "restorecon -R /var/www/html/user-repos/{{ gitea_user_name }}{{ user_number }}"
      changed_when: true


############
# Copy kickstart
############

    - name: Create kickstart users directory if it does not exist
      ansible.builtin.file:
        path:  /var/www/html/user-kickstarts/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}
        state: directory

    - name: Create tmp kickstart users directory if it does not exist
      ansible.builtin.file:
        path:  /tmp/user-kickstarts/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}
        state: directory

    - name: Download production kickstart
      shell: |
        curl -k -o /var/www/html/user-kickstarts/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}/kickstart.ks -H "Authorization: Basic $(echo -n '{{ gitea_user_name }}{{ user_number }}:{{  gitea_user_password }}{{ user_number  }}' | base64)" http://{{ ansible_hostname }}/{{ gitea_user_name }}{{ user_number }}/rhde/raw/branch/main/prod/rhde_image/kickstart.ks

    - name: Restore context on directory
      ansible.builtin.command: "restorecon -R /var/www/html/user-kickstarts/{{ gitea_user_name }}{{ user_number }}/{% raw %}{{ image_environment }}{% endraw %}"
      changed_when: true

