---
collections:
  - name: ansible.utils
    version: '*'
  - name: ansible.posix
  - name: awx.awx
  - name: community.aws
  - name: community.crypto
  - name: community.general
  - name: community.mysql
  - name: community.libvirt
  - name: kubernetes.core
  - name: containers.podman
  - name: redhat_cop.controller_configuration
  - name: fedora.linux_system_roles
  - name: https://github.com/ansible-collections/community.fdo.git
    type: git
  - name: https://github.com/luisarizmendi/infra.osbuild.git
    type: git