---
{% raw %}
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: "{% endraw %}{{ eda_webhook_port | default('5000') }}{% raw %}"

  rules:
    - name: Create new device image
      condition: "'production-image-definition.yml' in event.payload.commits[0].modified"
      action:
        run_workflow_template: 
          name: Provision Edge Device
          organization: "{{ event.payload.repository.owner.login | capitalize }} Organization"
          job_args:
            extra_vars:
              images_repo: "rhde/rhde_image"
              image_definition_file: "production-image-definition.yml"

    - name: Publish new device image
      condition:
        all:  
          - ('production-deploy_version.yml' in event.payload.commits[0].modified or 'production-kickstart.ks' in event.payload.commits[0].modified) 
          - 'production-image-definition.yml' not in event.payload.commits[0].modified
      action:
        run_job_template: 
          name: Publish Image
          organization: "{{ event.payload.repository.owner.login | capitalize }} Organization"
          job_args:
            extra_vars:
              images_repo: "device-edge-images"
              image_definition_file: "production-image-definition.yml"
              image_deploy_file: "production-image-deploy.yml"
              builder_blueprint_name: "production-{{ event.payload.repository.owner.login | capitalize }}"
              image_environment: "prod"

    - name: Initial provisioning 
      condition: 
        all: 
            - event.payload.ip_address is defined 
            - event.payload.mac_address is defined 
            - event.payload.user is defined
      action:
        run_workflow_template: 
          name: Provision Edge Device
          organization: "{{ user }} Organization"
          job_args:
            extra_vars:
              user: "{{ user }}"
              ip_address: "{{ ip_address }}"
              mac_address: "{{ mac_address }}"

{% endraw %}