---

- name: run a workflow on controller
  hosts:
    - all
  gather_facts: false
  vars:
    controller_hostname: "{{ ansible_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_validate_certs: false
    controller_workflow_launch_jobs:
      - name: New Edge Device Image
        wait: true
{% raw %}
        organization: "{{ username }} Organization"
{% endraw %}
  roles:
    - /opt/eda/collections/ansible_collections/redhat_cop/controller_configuration/roles/workflow_launch
