---
    - name: Install Git CLI
      become: true
      ansible.builtin.dnf:
        state: latest
        name: "git"

    - name: Open TCP ports for AAP Controller
      become: true
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        zone: public
      loop:
        - "{{ gitea_port | default('3000') }}/tcp"

    - name: Reload firewall
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/{{ ansible_user }}/gitea

    - name: Allow containers to access and modify files
      become: true
      shell: |
        semanage fcontext -a -t container_file_t '/home/{{ ansible_user }}/gitea(/.*)?'
        restorecon -R /home/{{ ansible_user }}/gitea

    - name: Check if container with name "gitea" exists
      containers.podman.podman_container_info:
        name: gitea
      register: container_info
      ignore_errors: true

    - name: Start Gitea container
      when: "'Error: no such container gitea' in container_info.stderr"
      containers.podman.podman_container:
        name: gitea
        image: docker.io/gitea/gitea:{{ gitea_version }}
        state: started
        ports:
          - "{{ gitea_port | default('3000') }}:{{ gitea_port | default('3000') }}"
          - 222:22
        env:
          USER_UID: "1000"
          USER_GID: "1000"
          GITEA__security__INSTALL_LOCK: true
        volumes:
          - /home/{{ ansible_user }}/gitea:/data
          - /etc/localtime:/etc/localtime:ro


    - name: Ensure /home/{{ ansible_user }}/.config/systemd/user directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/{{ ansible_user }}/.config/systemd/user/default.target.wants
        - /home/{{ ansible_user }}/.config/systemd/user/multi-user.target.wants

    - name: Copy systemd service unit template
      template:
        src: gitea.service.j2
        dest: /home/{{ ansible_user }}/.config/systemd/user/gitea.service

    - name: Enable Gitea systemd service
      shell: |
        ln -s /home/{{ ansible_user }}/.config/systemd/user/gitea.service /home/{{ ansible_user }}/.config/systemd/user/default.target.wants/gitea.service
        ln -s /home/{{ ansible_user }}/.config/systemd/user/gitea.service /home/{{ ansible_user }}/.config/systemd/user/multi-user.target.wants/gitea.service
        systemctl --user daemon-reload

