---

- name: Generate AAP config
  delegate_to: localhost
  template:
    src: "{{ aap_config_template }}"
    dest: /tmp/aap_config.yml

- name: Load variables
  ansible.builtin.include_vars: "/tmp/aap_config.yml"




### EDA

- name: configure EDA users
  when: eda_users_yaml is defined
  ansible.builtin.include_role:
    name: infra.eda_configuration.user
  vars:
    eda_users: "{{ eda_users_yaml|from_yaml }}"


## User specific (needs to look over users)

- name: configure EDA credentials
  when: eda_credentials is defined
  ansible.builtin.include_role:
    name: infra.eda_configuration.credential

- name: configure EDA projects
  when: eda_projects is defined
  ansible.builtin.include_role:
    name: infra.eda_configuration.project




