---
- name: create initial gitea user
  ansible.builtin.shell:
    cmd: podman exec -it {{ gitea_container | default('gitea') }} su git -c "/app/gitea/gitea admin user create --username {{ gitea_admin_name | default('gitea')}} --password '{{ gitea_admin_password | default('gitea')}}' --email 'dont@email.me' --admin"
  register: gitea_user_create
  changed_when:
    - "'created' in gitea_user_create.stdout"
  failed_when:
    - "'created' not in gitea_user_create.stdout"
    - "'already exists' not in gitea_user_create.stdout"


- name: Multiple gitea user configuration
  when: gitea_user_count is defined and gitea_user_count != 0
  block:
    - name: create multiple gitea user
      ansible.builtin.shell:
        cmd: podman exec -it {{ gitea_container | default('gitea') }} su git -c "/app/gitea/gitea admin user create --username {{ gitea_user_name }}{{ user_number }} --password '{{ gitea_user_password }}{{ user_number }}' --email '{{ gitea_user_name }}{{ user_number }}@email.me' --must-change-password=false "
      register: gitea_user_create
      changed_when:
        - "'created' in gitea_user_create.stdout"
      failed_when:
        - "'created' not in gitea_user_create.stdout"
        - "'already exists' not in gitea_user_create.stdout"
      loop: "{{ range(1, (gitea_user_count + 1), 1)|list }}"
      loop_control:
        loop_var: user_number


    - name: Create repos per user
      block: 
        - name: Find template files
          delegate_to: localhost
          ansible.builtin.find:
            paths: "{{ gitea_user_repos_template }}"
            patterns: "*"
            recurse: yes
            file_type: file 
          register: _template_files

        - name: Crop template file paths
          set_fact:
            _template_files_crop: "{{ _template_files.files | map(attribute='path') | map('regex_replace', '^' + gitea_user_repos_template + '/?', '') | list }}"

        - name: Extract template directories
          set_fact:
            _template_directories: "{{ _template_files_crop | map('dirname') | unique | list }}"

        - name: Extract repo names
          set_fact:
            repo_names: "{{ _template_directories | map('split', '/') | map('first') | unique | list }}"

        - name: Create directories for user repos
          file:
            path: "{{ gitea_user_repos_target | default('/tmp/gitea_user_repos') }}/{{ gitea_user_name }}{{ item.0 }}/{{ item.1 }}"
            state: directory
          loop: "{{ range(1, gitea_user_count + 1) | product(_template_directories) | list }}"

        - name: Create local git repos
          ansible.builtin.shell: |
            cd {{ gitea_user_repos_target | default('/tmp/gitea_user_repos') }}/{{ gitea_user_name }}{{ item.0 }}/{{ item.1 }}
            if [ ! -d .git ]; then 
            git init
            git checkout -b main
            git config user.name "{{ gitea_user_name }}{{ item.0 }}"
            git config user.email "dont@email.me"
            fi
          loop: "{{ range(1, gitea_user_count + 1) | product(repo_names) | list }}"

        - name: Copy template files to user repos
          ansible.builtin.template:
            src: "{{ gitea_user_repos_template }}/{{ item.0 }}"
            dest: "{{ gitea_user_repos_target | default('/tmp/gitea_user_repos') }}/{{ gitea_user_name }}{{ item.1 }}/{{ item.0 }}"
          loop: "{{ _template_files_crop | product(range(1, gitea_user_count + 1)) | list }}"
          vars:
            user_number: "{{ item.1 }}"

        - name: create repos in Gitea
          ansible.builtin.uri:
            url: "http://{{ ansible_host }}:{{ gitea_port | default('3000') }}/api/v1/admin/users/{{ gitea_user_name }}{{ item.0 }}/repos"
            validate_certs: false
            user: "{{ gitea_admin_name }}"
            password: '{{ gitea_admin_password }}'
            force_basic_auth: true
            body_format: json
            method: POST
            body:
              name: "{{ item.1 }}"
              private: true
            status_code:
              - 201
              - 409
          with_nested: 
            - "{{ range(1, (gitea_user_count + 1), 1)|list }}"
            - "{{ repo_names }}"

        - name: Commit repositories
          ignore_errors: true
          ansible.builtin.shell: |
            cd {{ gitea_user_repos_target | default('/tmp/gitea_user_repos') }}/{{ gitea_user_name }}{{ item.0 }}/{{ item.1 }}
            git checkout -b main
            git add .
            git commit -m "initial commit"
            git remote add origin http://{{ gitea_user_name }}{{ item.0 }}:{{ gitea_user_password }}{{ item.0 }}@{{ ansible_host }}:{{ gitea_port | default('3000') }}/{{ gitea_user_name }}{{ item.0 }}/{{ item.1 }}.git
          loop: "{{ range(1, gitea_user_count + 1) | product(repo_names) | list }}"

        - name: Push repositories
          ansible.builtin.shell: |
            cd {{ gitea_user_repos_target | default('/tmp/gitea_user_repos') }}/{{ gitea_user_name }}{{ item.0 }}/{{ item.1 }}
            git checkout -b main
            git push -u origin main
          loop: "{{ range(1, gitea_user_count + 1) | product(repo_names) | list }}"
