---
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: multicloud-gitops
  namespace: openshift-operators
spec:
  gitSpec:
    pollInterval: 180
    multiSourceSupport: false
    targetRepo: 'https://github.com/luisarizmendi/multicloud-gitops'
    targetRevision: main
  multiSourceConfig:
    clusterGroupChartGitRevision: main
    enabled: true
  clusterGroupName: hub