---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: app2048
  name: app2048
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2048
  name: app2048
  namespace: app2048 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2048
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2048
    spec:
      containers:
      - image: quay.io/luisarizmendi/2048:prod
        imagePullPolicy: IfNotPresent
        name: app2048
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File           
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: app2048
spec:
  selector:
    app: app2048
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: app2048
spec:
  port:
    targetPort: 8081 
  to:
    kind: Service
    name: test-service
    weight: 10