---


- name: create initial gitea user
  ansible.builtin.shell:
    cmd: podman exec -it {{ gitea_container | default('gitea') }} su git -c "/app/gitea/gitea admin user create --username lab-instructor --password '{{ admin_password }}' --email 'dont@email.me' --admin"
  register: gitea_user_create
  changed_when:
    - "'created' in gitea_user_create.stdout"
  failed_when:
    - "'created' not in gitea_user_create.stdout"
    - "'already exists' not in gitea_user_create.stdout"

