---
ocp_release: 4.14

microshift_image_pull_secret_template: pull_secret.j2
# PULL SECRET ENCRIPTED WITH ANSIBLE VAULT IN secrets.yaml


microshift_config_template: microshift_config.j2
microshift_config: 
  baseDomain: $(hostname -I | awk '{print $1}').nip.io
  clusterNetwork: 10.42.0.0/16
  serviceNetwork: 10.43.0.0/16
  serviceNodePortRange: 30000-32767
  hostnameOverride: microshift
  nodeIP: $(hostname -I | awk '{print $1}')
  subjectAltNames:
    - microshift.lablocal
    - microshift.$(hostname -I | awk '{print $1}').nip.io
  logLevel: Normal

microshift_test_app_template: test_app.j2
microshift_test_app_name: test


#microshift_image_crio_proxy_template: crio_proxy.j2
microshift_image_crio_proxy:
  user: 
  password: 
  server: 
  port: 


#microshift_image_ovn_options_template: ovn_options.j2
microshift_image_external_gateway_interface: enp1s0
microshift_image_gateway_interface: enp1s0
microshift_image_mtu: 1400



microshift_image_firewall_options:
  # network_access_to_pods (mandatory)
  - zone: trusted
    source: 10.42.0.0/16
  # network_access_to_services (mandatory)
  - zone: trusted
    source: 169.254.169.1
  # network_optional
  - zone: public
    port: 80/tcp
  - zone: public
    port: 443/tcp
  - zone: public
    port: 6443/tcp


rhc_state: present

builder_request_timeout: 300
builder_wait_compose_timeout: 2400
builder_blueprint_name: demo-microshift
builder_compose_type: edge-installer
builder_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
builder_skip_repo: false
builder_rhsm_repos:
- "rhocp-{{ ocp_release }}-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
- "fast-datapath-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
builder_compose_pkgs:
  - microshift
  - microshift-greenboot
  - NetworkManager-wifi
  - firewalld
  - git
  - openshift-clients
builder_compose_customizations:
  user:
    name: "admin"
    description: "Admin user"
    password: "R3dh4t1!"
    key: "{{ builder_pub_key }}"
    groups: ["users", "wheel"]
  services:
    enabled: ["microshift"]
  firewall.services:
    enabled: ["80/tcp", "8080/tcp", "443/tcp", "6443/tcp"]
builder_kickstart_options:
  - lang en_US.UTF-8
  - keyboard us
  - timezone Etc/UTC
  - text
  - zerombr
  - clearpart --all --initlabel
  - part /boot/efi --fstype=efi --size=200
  - part /boot --fstype=xfs --asprimary --size=800
  - part swap --fstype=swap --recommended
  - part pv.01 --grow
  - volgroup rhel pv.01
  - logvol / --vgname=rhel --fstype=xfs --size=10000 --name=root
  - reboot
  - network --bootproto=dhcp
#  - user --name={{ builder_compose_customizations['user']['name'] }} {{ "--password" if builder_password is defined  }} {{ builder_password if builder_password is defined }} --group=wheel,user  # noqa yaml[line-length]
  - ostreesetup --nogpg --osname=rhel --remote=edge --url=http://{{ ansible_host }}/{{ builder_blueprint_name }}/repo/ --ref={{ builder_blueprint_ref }}
additional_kickstart_post:
  - "{{ lookup('ansible.builtin.template', '../templates/firewall_options.j2') }}"
  - "{{ lookup('ansible.builtin.template', '../templates/{{ microshift_image_ovn_options_template }}') if microshift_image_ovn_options_template is defined | default(None) }}"
  - "{{ lookup('ansible.builtin.template', '../templates/{{ microshift_image_pull_secret_template }}') if microshift_image_pull_secret_template is defined | default(None) }}"
  - "{{ lookup('ansible.builtin.template', '../templates/{{ microshift_image_crio_proxy_template }}') if microshift_image_crio_proxy_template is defined | default(None) }}"
  - "{{ lookup('ansible.builtin.template', '../templates/{{ microshift_test_app_template }}') if microshift_test_app_template is defined | default(None) }}"
  - "{{ lookup('ansible.builtin.template', '../templates/{{ microshift_config_template }}') if microshift_config_template is defined | default(None) }}"
